/** ⓘ info-modal texts — ported VERBATIM from dashboard_app.js showInfo().
 *  Bodies are HTML strings (rendered via dangerouslySetInnerHTML after the
 *  same newline/bullet transforms the vanilla code applied). */

export interface InfoEntry { title: string; body: string }

const HR = '<hr style="border:0;border-top:1px solid var(--border);margin:-4px 0 12px 0">';

export const INFO: Record<string, InfoEntry> = {
  overall_usage: { title: 'OVERALL USAGE', body: HR + 'Shows the total proportion of commands originating from each source.\n\n<span style="color:var(--blue)">•</span> HUB: Hub originated events like automations and scenes.\n<span style="color:var(--blue)">•</span> APP (Local): Commands from the app while on the same Wi-Fi network.\n<span style="color:var(--blue)">•</span> DOCK: Commands from physical dock button presses.\n<span style="color:var(--blue)">•</span> APP (Remote): Commands from the app while away from home.\n\nAnalyze this chart to understand how users interact with the system.' },
  usage_trend: { title: 'USAGE TREND', body: HR + 'Provides a daily breakdown of system interactions across all control sources.\n\n<span style="color:var(--blue)">•</span> HUB: Hub originated events like automations and scenes.\n<span style="color:var(--blue)">•</span> APP: Manual interactions initiated through the mobile app (Local & Remote).\n<span style="color:var(--blue)">•</span> DOCK: Physical interactions via dock button presses.\n\nMonitor these trends over time to understand user behavior. A steady shift away from manual App usage towards Hub and Dock controls often indicates a well-automated, highly optimized smart home environment.' },
  fleet_total: { title: 'TOTAL EVENTS', body: 'The total number of commands successfully processed across the entire system. This count includes all actions originating from the APP + DOCK + HUB.' },
  fleet_reliability: { title: 'RELIABILITY', body: 'Measures the percentage of commands successfully executed by the system out of all commands attempted.\n\n<b>Formula:</b> (Successful Commands / Total Attempted Commands) × 100\n\n<b>Ranges:</b>\n• Good: > 97%\n• Acceptable: 95% - 97%\n• Bad: < 95%' },
  fleet_latency: { title: 'P50 SPEED', body: 'The median response time for commands. Exactly half of all commands are processed faster than this speed, providing a realistic view of typical system performance.\n\n<b>Formula:</b> The median of the 50th percentile value of all hubs.\n\n<b>Ranges:</b>\n• Good: < 800ms\n• Acceptable: 800ms - 1000ms\n• Bad: > 1000ms' },
  fleet_northstar: { title: 'NORTH STAR', body: 'The ultimate performance metric reflecting a flawless user experience, defined as the percentage of all commands that complete almost instantly.\n\n<b>Formula:</b> ROUND(100 × COUNT(latency_ms < 1000) / NULLIF(COUNT(latency_ms IS NOT NULL), 0), 2)\n\n<b>Ranges:</b>\n• Good: > 95%\n• Acceptable: 80% - 95%\n• Bad: < 80%' },
  hub_total: { title: 'TOTAL EVENTS', body: 'The total number of commands successfully processed across this system. This count includes all actions originating from the APP + DOCK + HUB.' },
  hub_reliability: { title: 'RELIABILITY', body: 'Measures the percentage of commands successfully executed by the system out of all commands attempted.\n\n<b>Formula:</b> (Successful Commands / Total Attempted Commands) × 100\n\n<b>Ranges:</b>\n• Good: > 97%\n• Acceptable: 95% - 97%\n• Bad: < 95%' },
  hub_latency: { title: 'P50 SPEED', body: 'The median response time for commands. Exactly half of all commands are processed faster than this speed, providing a realistic view of typical system performance.\n\n<b>Formula:</b> The 50th percentile value of all end-to-end command execution times.\n\n<b>Ranges:</b>\n• Good: < 800ms\n• Acceptable: 800ms - 1000ms\n• Bad: > 1000ms' },
  hub_failures: { title: 'FAILURES', body: 'The total number of commands that failed to complete on this hub. In our context, a failure means the system could not successfully execute a command.\n\nThis total includes:\n• App Failures: Commands sent from the user app that failed\n• Dock Failures: Physical docklet presses that failed\n• Hub Failures: Automated scene or schedule executions from the hub that failed' },
  daily_chart: { title: 'DAILY EVENTS & RELIABILITY', body: HR + 'A day-by-day breakdown of system activity and its success rate.\n\n• Hub Events (Violet): Hub originated events like automations and scenes.\n• App Events (Blue): Manual controls from the user app.\n• Dock Events (Orange): Physical dock button presses.\n• Reliability % (Green Dotted Line): Percentage of total commands that successfully executed.\n• Target % (Grey Dotted Line): The 97% reliability is the goal.\n\nA dip in the green line indicates system issues on that day.' },
  p50_chart: { title: 'P50 & P95 SPEED TREND', body: HR + 'Tracks the median (P50) and worst-case (P95) response times of system commands over time.\n\n• P50 Speed (ms) (Orange Line with Dot): The median response time where 50% of all commands finished faster than this value.\n• P95 Speed (ms) (Red Line with Dot): The worst-case response time where 95% of all commands finished faster than this value.\n• Target (ms) (Grey Dotted Line): The target response time is <1000ms.\n\nIf the red or orange lines spike above the target line, it indicates the system was abnormally slow on that day.' },
  ns_chart: { title: 'NORTH STAR TREND', body: HR + 'Tracks the percentage of commands that completed almost instantly (under 1 second) over time.\n\n• North Star % (Blue Line with Dot): The percentage of lightning-fast commands for that day.\n• Target % (Grey Dotted Line): The baseline goal of 95%.\n\nDrops in the blue line usually indicate temporary network congestion, a struggling device, or Thread mesh instability. Investigating these dips helps maintain a flawless user experience.' },
  fail_trend_chart: { title: 'FAILURES TREND', body: HR + 'Breaks down exactly which commands failed each day across the system.\n\n• Hub Failures (Violet): Failures from automated hub scenes and schedules.\n• App Failures (Red): Failures from manual controls via the user app.\n• Dock Failures (Orange): Failures from physical dock button presses.\n\nMonitor this graph to easily identify if a spike in unreliability is caused by a specific source (e.g., dock commands failing constantly).' },
  heatmap: { title: 'ACTIVITY HEATMAP', body: HR + 'Shows when devices are controlled most across the entire week.\n\n• Dark Blue: High volume of commands during this hour.\n• Light/Black: Low or no activity during this hour.\n\nAnalyze this grid to spot usage patterns, like most activity happening on weekday evenings.' },
  heatmap_fail: { title: 'FAILURES HEATMAP', body: HR + 'Shows when system failures happen most across the entire week.\n\n• Dark Red: High volume of failures during this hour.\n• Light/Black: Low or no failures during this hour.\n\nAnalyze this grid to spot recurring failure patterns. A cell glowing red at the same time every day points to environmental interference, router reboots, or scheduled congestion.' },
  lat_cdf: { title: 'CUMULATIVE DISTRIBUTION FUNCTION', body: HR + 'A Cumulative Distribution Function (CDF) graph plotting Latency versus Percentile.\n\n• Percentile (X-axis): The percentage of commands.\n• Latency (Y-axis): The maximum response time for that percentage of commands.\n• Target (Grey Dotted Line): The latency target (1000ms).\n\nThis graph shows the overall distribution of command speeds. A curve that stays below the target line for the vast majority of percentiles means the system is performing well.' },
  speed_segments: { title: 'SPEED SEGMENTS', body: HR + 'Breaks down where time is actually spent when a command is sent. There are 4 roundtrips:\n\n• Hub &rarr; SNAP &rarr; Hub (Automations & Scenes): How long for the hub to command the physical device and get state confirmed back.\n• Hub &rarr; App (WebSocket Push): How long for the hub to push the new state to the phone via WebSocket.\n• App Control (Local): Full round trip when the user is on the same Wi-Fi as the hub.\n• App Control (Remote): Full round trip when controlling from outside the home.\n\nCompare these segments to identify bottlenecks. If App Control is slow but Hub &rarr; SNAP is fast, the delay is in the network or WebSocket connection.' },
  lat_dist: { title: 'SPEED DISTRIBUTION', body: HR + 'How many commands fell into each speed bucket:\n\n• Green (<500ms): Fast & feels instant\n• Yellow (500ms-1s): Acceptable\n• Orange (1-2s): Getting slow\n• Red (2-5s): Noticeably sluggish\n• Deep Red (>5s): Very slow & investigate\n\nA healthy system has the vast majority of events in the green bucket.' },
  uc_lat: { title: 'Latency by Use Case', body: 'Compares speed across the different ways devices can be controlled:\n\n• App Control: User tapped the phone app on local Wi-Fi\n• Dock Control: Physical dock button was pressed\n• Remote App: User controlled from outside the home\n• Observed Change: State change detected by the hub (e.g. manual switch)\n\nShows Avg, P50 (typical), and P95 (worst-case). Useful for spotting if one control method is consistently slower.' },
  uc_table: { title: 'Per Use Case Speed', body: 'Detailed latency numbers for each control method. The most important column is P95 — it represents the slowest 5% of commands, your worst-case user experience. P95 above 1 second is flagged as Critical and should be investigated. Click any row for event-level detail.' },
  uc_speed_metrics: { title: 'Speed Metrics Explained', body: 'Every use-case card shows four numbers:\n\n• Avg — The simple average of all command times. Easy to read but one very slow event can pull it up and make things look worse than they are.\n\n• P50 (Median) — Sort all command times; P50 is the middle value. Half finished faster, half slower. This is what a typical user actually experiences day-to-day.\n\n• P95 — 95% of commands finished faster than this number. Only the slowest 5% were slower. This is your worst-case experience — if P95 is under 1000ms, even your slowest users are getting a decent experience.\n\n• Std Dev (Standard Deviation) — Measures how consistent the times are. A low number means most commands take a similar amount of time (predictable). A high number means some are fast and some are very slow (erratic). Green under 200ms · Yellow 200–500ms · Red above 500ms.' },
  rel_kpis: { title: 'Reliability KPIs', body: 'Two ways of measuring how reliably commands are confirmed:\n\n• App Trigger Feedback: When a user taps in the app, does the app receive confirmation that the command worked? This is the most direct measure of app-facing reliability.\n• Dock Trigger Reliability: When a physical dock button is pressed, does the bound device actually activate? Computed from hub logs (ha_logs) — the reliable, always-on source.\n\nClick either card to debug failures for that source.' },
  rel_source: { title: 'RELIABILITY BY SOURCE', body: HR + 'Reliability broken down by how the device was controlled.\n\n• APP CONTROL: Commands sent from the mobile app.\n• DOCK CONTROL: Commands triggered by pressing a physical dock button.\n• HUB: Everything the hub originated - automation runs and scene activations.\n\nIt pinpoints whether one control method is failing more than others.' },
  rel_trend: { title: 'RELIABILITY TREND', body: HR + "How reliability changed over the selected period across the entire system.\n\n• Reliability percentage (Green line with dot): The daily success rate of all commands.\n• Target % (Dashed Line): The minimum acceptable reliability target.\n\nA sustained drop indicates a persistent problem. A one-day drop usually points to a temporary event like a power outage or network hiccup." },
  dock_rel: { title: 'DOCK RELIABILITY', body: HR + 'Reliability per physical dock device, computed from hub logs.\n\nA docklet press is a hub-recorded command; it succeeds when the bound SNAP device actually reached a real state (on/off), and fails when it did not respond.\n\nEach row shows one dock, how many presses succeeded versus failed.' },
  fail_reason: { title: 'FAILURES BY REASON', body: HR + "Groups all system failures by their root cause.\n\n• TIMEOUT: Command reached the hub but the device didn't respond in time.\n• DEVICE_OFFLINE: Device wasn't reachable when the command was sent.\n• NO_RESPONSE: Hub got no acknowledgement from the device.\n• THREAD_MESH_FAIL: The wireless mesh dropped the packet before reaching the device.\n• DEVICE_UNAVAILABLE: Device was disconnected from the network.\n\nAnalyze these reasons to identify network or device-specific issues causing command failures." },
  fail_device: { title: 'FAILURES BY DEVICE', body: HR + 'Identifies which individual lights or switches are failing the most frequently.\n\nIf one device appears here consistently, it likely needs attention.' },
  usage_auto: { title: 'AUTOMATION / DAY', body: HR + 'The average number of automated background routines triggered by the hub per day.' },
  usage_scene: { title: 'SCENE / DAY', body: HR + 'The average number of multi-device preset scenes activated by the hub per day.' },
  usage_snap_devices: { title: 'ACTIVE SNAP DEVICES', body: HR + 'SNAP devices are physical smart hardware connected to the system. Counts unique physical hardware (e.g. lights, switches, fans) that received commands in the selected period. Excludes virtual entities like scenes and automations.' },
  usage_app: { title: 'APP USAGE', body: HR + 'Visualizes the digital interactions generated by the mobile app.\n\n• TOTAL APP EVENTS: The total count of app interactions recorded.\n• APP (LOCAL): Events triggered on the same Wi-Fi as the hub.\n• APP (REMOTE): Events triggered from outside the home.\n• ACTION TYPE COUNT: A breakdown showing exactly what kind of commands were sent (e.g. Toggle, Brightness adjustment).' },
  usage_dock: { title: 'DOCK USAGE RATIO', body: HR + 'Share of all activity that originated from physical dock buttons, out of App + Dock + Hub. The three ratios add up to 100%.' },
  usage_ha_ui: { title: 'DIRECT HUB CONTROL', body: HR + "Devices driven directly from the hub's own Home Assistant screen — not the mobile app, a dock, an automation or a scene.\n\nIdentified by the hub's actuation_source field (ha:*), which records the real origin of each actuation, restricted to controllable devices (light, switch, fan, …) that reached a concrete state. It is counted in Total Events / Reliability and grouped under the Hub source alongside automation runs and scene activations." },
  src_chart: { title: 'Source Breakdown', body: 'A visual split of all events by how they were triggered:\n\n• App (Local): User tapped the phone app on the same Wi-Fi\n• Remote App: User tapped the app from outside the home\n• Dock Control: Physical dock button was pressed\n• Observed Change: State change detected automatically (e.g. manual switch, scene activation)\n\nClick any segment to see those specific events in the Log Center.' },
  dock_usage: { title: 'DOCK USAGE', body: HR + 'Visualizes the physical interactions and action types generated by smart docks in the system.\n\n• TOTAL DOCK EVENTS: The total count of dock button presses recorded during this period.\n• TOTAL DOCKS: The total number of physical dock units active in the system.\n• ACTIVE DOCKLETS: The number of distinct individual dock buttons that were used.\n• ACTION TYPE COUNT: A breakdown showing exactly what kind of commands were sent (Toggle on/off, Increment brightness/volume, Decrement brightness/volume).' },
  dev_activity: { title: 'Device Activity', body: "A ranked list of every device (light or switch) controlled through this hub, sorted by most-used first. Shows:\n\n• Device: The entity ID (short name) of the device\n• Room: Which room it's in\n• Events: Total commands sent to this device in the selected period\n• Reliability: What percentage of commands on this device succeeded\n• P50: The median response time for this specific device\n\nClick any row to see the full stats for that device including its failure events." },
  log_center: { title: 'Log Center', body: 'A detailed event-level workspace for debugging. Every command event appears here with its timestamp, device, room, control method, latency, and failure reason.\n\nHow to use it:\n• Failures tab: Shows only failed commands — start here when investigating an issue\n• Slow Events tab: Shows commands that took over 800ms\n• All Events tab: Every event in the selected period\n• Source / Reason filters: Narrow down to a specific control method or failure type\n• Search box: Filter by device name, room, or date\n• Click any row: Expands a visual timing pipeline showing exactly where time was spent in that specific command' },
};

/** Same body transform the vanilla showInfo applied. */
export function infoBodyHtml(body: string): string {
  return body
    .replace(/\n\n/g, '<br><br>')
    .replace(/\n/g, '<br>')
    .replace(/•/g, '<span style="color:var(--blue);margin-right:2px">•</span>');
}
